[build-system]
requires = [
         "setuptools >= 42",
         "wheel",
         "setuptools_scm[toml] >= 7.0.1",
         "numpy   >= 1.16.3",
         "pandas  >= 0.23.4",
         "statsmodels >= 0.13.0",
         "autograd >= 1.5",
         "numdifftools >=0.9.40",
         "scipy >= 1.9.2",
         "pandas >= 1.4.0",
         "matplotlib >=3.6.0",
         "seaborn >= 0.11.0"
         ]
build-backend = "setuptools.build_meta"

[project]
name = "dts"
description = "Distributed Time Series Modeling with Apache Spark"
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["version"]

[tool.setuptools]
py-modules = ["dts"]

[tool.setuptools_scm]
version_scheme = "release-branch-semver"
write_to = "dts/_version.py"
fallback_version = "0.1.0"

[tool.poetry]
authors = [
    "Feng Li <feng.li@cufe.edu.cn>",
    "Zixuan Wang <zixuan.wang-2@student.uts.edu.au>",
    "Matias Quiroz <quiroz.matias@gmail.com>"
    ]

repository = "https://github.com/feng-li/dts"
keywords = ["Spark", "MCMC", "MapReduce"]
license = "MIT"
