# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.0.dev26+g2f98b47.d20221114'
__version_tuple__ = version_tuple = (0, 1, 0, 'dev26', 'g2f98b47.d20221114')
